site_name: Documentação
repo_name: "2024.2-Champions"
repo_url: https://github.com/FGA-REQ/2024.2-Champions

nav:
  - Página Inicial: "index.md"
  - Histórico de Versões: "historico/historico.md"
  - Regras de Negócio: "regras-negocio.md"
  - Declaração de Requisitos:
      - Histórias de Usuário: "dec/historias-usuario.md"
      - Fluxo de Usuário: "dec/fluxo-usuario.md"
      - Declaração: "dec/declaracao-requisitos.md"
      - Backlog do Produto: "dec/backlog.md"

theme:
  name: material
